### PR TITLE
Update pin and session selection buttons to use Javascript

### PR DESCRIPTION
**Pull request by rashansmith**
- Change session-selection and pin html element types from ```<input>``` to ```<button>```
- Implement API calls in Javascript and execute from html button click

### CODE REVIEW

**Comment by AlexeyAkhunov** [comment]
Thank you! Would you be able to do some refactoring of the Javascript functions to reduce the repetition of the code?

**Comment by rashansmith** [comment]
I combined the resume and switch session async functions, and also converted the form creation and API request creation lines of code into helper functions

**Comment by AlexeyAkhunov** [comment]
Thank you! Can you also clean up commented out `<div>` in the template file

**Comment by rashansmith** [comment]
The comments have been removed from the template file

**Pull request merged**
