### PR TITLE
NOTICKET: improving reorgs module

### PR DESCRIPTION
**Pull request by moldis**
This PR improving:

`Reorg scanner is very basic and it does not have a concept of a "deep" reorg (deeper than 1 block). For such situations, it will just show the consecutive block numbers as all having a reorg. It would be better to aggregate these into deep reorgs, and also perhaps show if there are more than 1 branch at each reorg point.`

TLTR:

- Separated UI calls from main code calls
- Added unit tests for reorgs (positive tests only, there is room to add more negative tests)
- Improved algo to scan duplicated over 1000 records (previously it was simply next line scan)

### CODE REVIEW

**Comment by AlexeyAkhunov** [comment]
Thank for the PR! Would you be able to update it, I have merged a PR with large refactoring

**Comment by moldis** [comment]
@AlexeyAkhunov synced!

**Comment by AlexeyAkhunov** [comment]
Thank you! Could you merge the latest `main`, I have fixed CI errors there

**Comment by moldis** [comment]
@AlexeyAkhunov it should be synced now.

**Comment by AlexeyAkhunov** [comment]
Thank you, I will merge it as is, will review/test later. Will also contact you by email (I've got your email)

**Pull request merged**
